
env = Environment(PIC='24FJ128GB206',
                  CC='xc16-gcc',
                  PROGSUFFIX='.elf',
                  CFLAGS='-g -omf=elf -x c -mcpu=$PIC',
                  LINKFLAGS='-omf=elf -mcpu=$PIC -Wl,--script="app_p24FJ128GB206.gld"',
                  CPPPATH=['../lib'])
env.PrependENVPath('PATH', '/opt/microchip/xc16/v1.25/bin')
env.PrependENVPath('PATH', '/opt/microchip/xc16/v1.25/bin')
bin2hex = Builder(action='xc16-bin2hex $SOURCE -omf=elf',
                  suffix='hex',
                  src_suffix='elf')
env.Append(BUILDERS={'Hex': bin2hex})
build_list = Builder(action='xc16-objdump -S -D $SOURCE > $TARGET',
               suffix='lst',
               src_suffix='elf')
env.Append(BUILDERS={'List': build_list})

env.Program('rocket_main', ['main.c',
                            '../lib/pin.c',
                            '../lib/ui.c',
                            '../lib/timer.c',
                            '../lib/quad.c',
			    '../lib/pid.c',
                            '../lib/i2c.c',
                            '../lib/servo.c',
                            '../lib/uart.c'])
env.Hex('rocket_main')
env.List('rocket_main')
